### ISSUE TITLE
pingdom whitelist in bytes

### ISSUE THREAD

**Issue by gravitybacklight** [PicnicSupermarket/pingdom-probes-aws-whitelist#1]
Running on linux, the returned whitelist ips are being set as bytes, so the script errors with:
`botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupIngress operation: CIDR block b'x.x.x.x'/32 is malformed`

decoding the ip variable solves the issue, but i guess it would be best to do detection on the file.

`def create_permission(self, ip):
        return Permission(self.protocol, '{0}/32'.format(ip.decode('UTF-8')), self.from_port, self.to_port)
`

**Comment by Stephan202** [comment]
Thanks for reporting this! I'll spend some time this afternoon to have a closer look. After a cursory look at the code and your proposed fix, I wonder whether it would be better to do the conversion directly in `SecurityGroupUpdater#get_ips`. WDYT?

**Comment by Stephan202** [comment]
Mind giving PR #2 a spin? :)

**Comment by gravitybacklight** [comment]
seems to work ok, thank you for you prompt fix.

**Comment by Stephan202** [comment]
Thank you again for reporting the issue. I should have tested against Python 3 in the first place :)
